### ISSUE TITLE
Do you have a ToDo list?

### ISSUE THREAD

**Issue by cphrmky** [Fryie/ipfs-ruby#1]
I'd be happy to jump on some items.

**Comment by Fryie** [comment]
Sure.

The goal is to provide an API compatible with the [reference implementation in Node](https://github.com/ipfs/node-ipfs-api) (albeit probably in a more Ruby-like style. async everywhere and callbacks is not very Ruby-ish).

The next and most important item on that list should be "add". In the simpler scenario we just accept a particular filename. In the more complex one, similar to the node API, we might consider lists of files or file contents in memory. Architecturally it might make sense to either use different methods for those scenarios or to make it configurable via parameters - I'm not sure yet.

With "add" implemented, I think the remaining commands can be tackled in any order.

If you can help out that would be super cool, being somewhat busy atm. :)

**Comment by logicminds** [comment]
What about mirroring many of the methods found in FileUtils class?  That way users will feel more at home.

*  mkdir_p
* rm_f
* rm_rf
* https://ruby-doc.org/stdlib-2.4.1/libdoc/fileutils/rdoc/FileUtils.html

And some of the file methods as well.
```ruby
IPFS::File.open('filename.txt', 'w') {|file| file.write('ipfs rules') }
IPFS::File.read('filename.txt', hash_id)`  # does this even make sense?
IPFS::File.write('filename.txt', 'ipfs rules')
```

**Comment by Fryie** [comment]
I've just updated the README to mention that I'm not maintaining this project any longer. If someone wants to maintain this, I'd be happy to transfer ownership.
