### ISSUE TITLE
proposed Module rename. ipfs-ruby => ruby-ipfs-http-client

### ISSUE THREAD

**Issue by daviddias** [Fryie/ipfs-ruby#7]
Hi! We are considering renaming the IPFS Client libraries, please read more at https://github.com/ipfs/ipfs/issues/374 and comment if you are onboard.

**Comment by Fryie** [comment]
I've just updated the README to mention that I'm not maintaining this project any longer. If someone wants to maintain this, I'd be happy to transfer ownership.
