### ISSUE TITLE
New IPFS Client Maintainers Group

### ISSUE THREAD

**Issue by mikeal** [Fryie/ipfs-ruby#8]
Hiya :)

In the IPFS org we’ve [created a new group](https://github.com/ipfs/community/issues/352#issuecomment-440380041) for maintainers of client libraries. This will make it easier for us to loop you into issues that may cause problems or necessitate changes in your client library.

If you could let us know the github usernames of all the active maintainers we can add them to the group and note them in the [clients table](https://github.com/ipfs/ipfs#http-client-libraries).

Also, we have a great [IPFS weekly newsletter](https://tinyletter.com/ipfsnewsletter). A few days before each edition goes out a new pull request is created [in the repo](https://github.com/ipfs/newsletter). If you have any announcements related to your client library feed free to log a new issue in the repo or just comment on an upcoming newsletter pull request.

**Comment by Fryie** [comment]
I've just updated the README to mention that I'm not maintaining this project any longer. If someone wants to maintain this, I'd be happy to transfer ownership.

**Comment by logicminds** [comment]
I would be happy to be another maintainer.

**Comment by Fryie** [comment]
@logicminds to clarify: do you want to take over this project or will you be working on https://github.com/tbenett/ruby-ipfs-api instead?

Either way, I can link to the relevant repo / fork from this repo's README and, if necessary, transfer ownership of the gem on rubygems.

**Comment by logicminds** [comment]
I would prefer to work on the ruby-ipfs-api as it appears to have more steam and offer more.  I would recommend adding the link.

**Comment by Fryie** [comment]
Done. Let me know if you need anything else.
